// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwZkiKdKztMcXGiW2gIS_Y52HB-zGeoP0',
    appId: '1:167584664566:web:2ff2e0546ec452119b15d7',
    messagingSenderId: '167584664566',
    projectId: 'electrical-store-c002f',
    authDomain: 'electrical-store-c002f.firebaseapp.com',
    storageBucket: 'electrical-store-c002f.appspot.com',
    measurementId: 'G-VVL76TVMCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKGdc-j74UEdu6MSBjwr4KJi8yEwiwXs0',
    appId: '1:167584664566:android:6c89e120cdcc155a9b15d7',
    messagingSenderId: '167584664566',
    projectId: 'electrical-store-c002f',
    storageBucket: 'electrical-store-c002f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRn2f4U0iOLstWFwUmnKzTMBfgzVBF-a8',
    appId: '1:167584664566:ios:b7d763cd83e2525a9b15d7',
    messagingSenderId: '167584664566',
    projectId: 'electrical-store-c002f',
    storageBucket: 'electrical-store-c002f.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRn2f4U0iOLstWFwUmnKzTMBfgzVBF-a8',
    appId: '1:167584664566:ios:9f6dd3bbf07ae8629b15d7',
    messagingSenderId: '167584664566',
    projectId: 'electrical-store-c002f',
    storageBucket: 'electrical-store-c002f.appspot.com',
    iosBundleId: 'com.example.storeApp.RunnerTests',
  );
}
